"""edit subgroups and name of subject

Revision ID: 683b1a0d8822
Revises: e1bd276d538b
Create Date: 2025-09-07 01:28:33.290844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683b1a0d8822'
down_revision = 'e1bd276d538b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_semester', schema=None) as batch_op:
        batch_op.alter_column('subgroup',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('student_semester', schema=None) as batch_op:
        batch_op.alter_column('subgroup',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))

    # ### end Alembic commands ###
