"""add subgroup to student_semester

Revision ID: e1bd276d538b
Revises: 
Create Date: 2025-09-06 22:59:41.910921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bd276d538b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('subgroup')

    with op.batch_alter_table('student_semester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subgroup', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_semester', schema=None) as batch_op:
        batch_op.drop_column('subgroup')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subgroup', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
